### ISSUE TITLE
duplicate files

### ISSUE THREAD

**Issue by larshp** [rulerunner/rulerunner4ABAP#6]
Class ZCL_RULERUNNER
https://github.com/rulerunner/rulerunner4ABAP/blob/master/src/zcl_rulerunner.clas.abap
https://github.com/rulerunner/rulerunner4ABAP/blob/master/src/main/zcl_rulerunner.clas.abap
exists twice, this will give problems

**Comment by rulerunner** [comment]
Hi Lars,
thx for checking my repository. Removed all duplicates. 
Cheers,
Derk

**Comment by larshp** [comment]
cool, project added to https://dotabap.org

**Comment by rulerunner** [comment]
Hi Lars, I just updated the repo description. Would you update this on dotabap.org. Derk

**Comment by larshp** [comment]
it updates automatically every 24 hours, so just wait another ~9 hours and it will be updated 😄

**Comment by rulerunner** [comment]
cool, thx, have a nice weekend
